name: userland

services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    environment:
      TRAEFIK_PING: "true"
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
    ports:
      - "80:80"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: ${TRAEFIK_MEM_LIMIT:-0}

networks:
  traefik: {}
