services:
  archivist:
    build:
      context: .
      dockerfile: Dockerfile
    image: userland/archivist
    pull_policy: build
    container_name: archivist
    restart: unless-stopped
    init: true
    environment:
      RESTIC_REPOSITORY: s3:${ARCHIVIST_S3_ENDPOINT:?}/${ARCHIVIST_S3_BUCKET:?}
      RESTIC_PASSWORD_COMMAND: archivist-key
      RESTIC_HOST: archivist
      AWS_ACCESS_KEY_ID: ${ARCHIVIST_S3_ACCESS_KEY_ID:?}
      AWS_SECRET_ACCESS_KEY: ${ARCHIVIST_S3_SECRET_ACCESS_KEY:?}
      AWS_DEFAULT_REGION: ${ARCHIVIST_S3_REGION:?}
      ARCHIVIST_KEY_PROVIDER: ${ARCHIVIST_KEY_PROVIDER:?}
      ARCHIVIST_KEY_NAME: ${ARCHIVIST_KEY_NAME:?}
      ARCHIVIST_KEY_REGION: ${ARCHIVIST_KEY_REGION:?}
      ARCHIVIST_KEY_ACCESS_KEY_ID: ${ARCHIVIST_KEY_ACCESS_KEY_ID:?}
      ARCHIVIST_KEY_SECRET_ACCESS_KEY: ${ARCHIVIST_KEY_SECRET_ACCESS_KEY:?}
    volumes:
      - backups:/backups
    healthcheck:
      test: ["CMD", "archivist", "health"]
      interval: 10s
      timeout: 5s
      retries: 1
    mem_limit: ${ARCHIVIST_MEM_LIMIT:-0}

volumes:
  backups: {}
